server:
  port: 9080

spring:
 profiles: default
 application:
  name: shelter
 datasource:
  url: jdbc:hsqldb:mem:shelter
  username: sa
  password:
  driverClassName: org.hsqldb.jdbcDriver

 jpa:
  database: HSQL
  show-sql: false
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.HSQLDialect

---

spring:
 profiles: production
 datasource:
  url: jdbc:mysql://localhost/shelter
  username: shelter
  driverClassName: com.mysql.jdbc.Driver
 jpa:
  database: MYSQL
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.MySQL5Dialect
   naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
