spring:
 datasource:
  url: jdbc:mysql://localhost:3306/shelter
  username: shelter
  password: shelter
  driverClassName: com.mysql.jdbc.Driver

 jpa:
  database: MYSQL
  show-sql: true
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.MySQL5Dialect
   naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy