server:
  port: 9080
  
event:
 frequency:
  second: 60

#same port for metrics
management:
 port: 9080

spring:
 profiles: default
 application:
  name: shelter
 datasource:
  url: jdbc:hsqldb:mem:shelter
  username: sa
  password:
  driverClassName: org.hsqldb.jdbcDriver
#use for p6spy logs : driverClassName: com.p6spy.engine.spy.P6SpyDriver 

 jpa:
  database: HSQL
  show-sql: false
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.HSQLDialect

---

spring:
 profiles: production
 datasource:
  url: jdbc:mysql://localhost/shelter
  username: shelter
  driverClassName: com.mysql.jdbc.Driver
 jpa:
  database: MYSQL
  show-sql: false
  hibernate:
   ddl-auto: create-drop
   dialect: org.hibernate.dialect.MySQL5Dialect
   naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
